[2025-03-21T13:32:48.270+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250321_131741 scheduled__2025-03-21T13:27:39.231672+00:00 [queued]>
[2025-03-21T13:32:48.315+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250321_131741 scheduled__2025-03-21T13:27:39.231672+00:00 [queued]>
[2025-03-21T13:32:48.324+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-21T13:32:48.426+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copy_to_hdfs_batch_20250321_131741> on 2025-03-21 13:27:39.231672+00:00
[2025-03-21T13:32:48.436+0000] {standard_task_runner.py:57} INFO - Started process 2337 to run task
[2025-03-21T13:32:48.453+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'copy_to_hdfs_batch_20250321_131741', 'scheduled__2025-03-21T13:27:39.231672+00:00', '--job-id', '635', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpflparxqq']
[2025-03-21T13:32:48.461+0000] {standard_task_runner.py:85} INFO - Job 635: Subtask copy_to_hdfs_batch_20250321_131741
[2025-03-21T13:32:48.691+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250321_131741 scheduled__2025-03-21T13:27:39.231672+00:00 [running]> on host 1b7c3466167a
[2025-03-21T13:32:49.216+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='rabiizahnoune7@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='copy_to_hdfs_batch_20250321_131741' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T13:27:39.231672+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T13:27:39.231672+00:00'
[2025-03-21T13:32:49.221+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-21T13:32:49.223+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            docker exec hive hdfs dfs -mkdir -p /data/transactions/transactions_batch_20250321_131741 &&             docker exec hive hdfs dfs -put -f /data/transactions/transactions_batch_20250321_131741.parquet /data/transactions/transactions_batch_20250321_131741/\n            ']
[2025-03-21T13:32:49.276+0000] {subprocess.py:86} INFO - Output:
[2025-03-21T13:33:03.644+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-03-21T13:33:03.675+0000] {process_utils.py:131} INFO - Sending 15 to group 2337. PIDs of all processes in the group: [2350, 2352, 2337]
[2025-03-21T13:33:03.685+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 2337
[2025-03-21T13:33:03.692+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-21T13:33:03.695+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-03-21T13:33:03.851+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2337, status='terminated', exitcode=0, started='13:32:48') (2337) terminated with exit code 0
[2025-03-21T13:33:03.854+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2352, status='terminated', started='13:32:49') (2352) terminated with exit code None
[2025-03-21T13:33:03.856+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2350, status='terminated', started='13:32:49') (2350) terminated with exit code None
