[2025-03-21T13:32:48.323+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250321_131230 scheduled__2025-03-21T13:27:39.231672+00:00 [queued]>
[2025-03-21T13:32:48.363+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250321_131230 scheduled__2025-03-21T13:27:39.231672+00:00 [queued]>
[2025-03-21T13:32:48.364+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-21T13:32:48.408+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copy_to_hdfs_batch_20250321_131230> on 2025-03-21 13:27:39.231672+00:00
[2025-03-21T13:32:48.425+0000] {standard_task_runner.py:57} INFO - Started process 2336 to run task
[2025-03-21T13:32:48.432+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'copy_to_hdfs_batch_20250321_131230', 'scheduled__2025-03-21T13:27:39.231672+00:00', '--job-id', '636', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpgkt_u1mn']
[2025-03-21T13:32:48.448+0000] {standard_task_runner.py:85} INFO - Job 636: Subtask copy_to_hdfs_batch_20250321_131230
[2025-03-21T13:32:48.677+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250321_131230 scheduled__2025-03-21T13:27:39.231672+00:00 [running]> on host 1b7c3466167a
[2025-03-21T13:32:49.300+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='rabiizahnoune7@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='copy_to_hdfs_batch_20250321_131230' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T13:27:39.231672+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T13:27:39.231672+00:00'
[2025-03-21T13:32:49.318+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-21T13:32:49.320+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            docker exec hive hdfs dfs -mkdir -p /data/transactions/transactions_batch_20250321_131230 &&             docker exec hive hdfs dfs -put -f /data/transactions/transactions_batch_20250321_131230.parquet /data/transactions/transactions_batch_20250321_131230/\n            ']
[2025-03-21T13:32:49.402+0000] {subprocess.py:86} INFO - Output:
[2025-03-21T13:33:03.725+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-03-21T13:33:03.756+0000] {process_utils.py:131} INFO - Sending 15 to group 2336. PIDs of all processes in the group: [2367, 2370, 2336]
[2025-03-21T13:33:03.758+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 2336
[2025-03-21T13:33:03.760+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-21T13:33:03.761+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-03-21T13:33:03.939+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2367, status='terminated', started='13:32:49') (2367) terminated with exit code None
[2025-03-21T13:33:03.940+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2370, status='terminated', started='13:32:49') (2370) terminated with exit code None
[2025-03-21T13:33:03.941+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2336, status='terminated', exitcode=0, started='13:32:48') (2336) terminated with exit code 0
