[2025-03-20T02:35:06.075+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.create_hive_table scheduled__2025-03-20T01:44:58.253415+00:00 [queued]>
[2025-03-20T02:35:06.086+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.create_hive_table scheduled__2025-03-20T01:44:58.253415+00:00 [queued]>
[2025-03-20T02:35:06.087+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-20T02:35:06.106+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): create_hive_table> on 2025-03-20 01:44:58.253415+00:00
[2025-03-20T02:35:06.115+0000] {standard_task_runner.py:57} INFO - Started process 1732 to run task
[2025-03-20T02:35:06.120+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'create_hive_table', 'scheduled__2025-03-20T01:44:58.253415+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpy9d_9lf3']
[2025-03-20T02:35:06.124+0000] {standard_task_runner.py:85} INFO - Job 226: Subtask create_hive_table
[2025-03-20T02:35:06.187+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.create_hive_table scheduled__2025-03-20T01:44:58.253415+00:00 [running]> on host 87980e846a97
[2025-03-20T02:35:06.240+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-03-20T02:35:06.297+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='create_hive_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T01:44:58.253415+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-20T01:44:58.253415+00:00'
[2025-03-20T02:35:06.299+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-20T02:35:06.301+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    docker exec hive beeline -u "jdbc:hive2://localhost:10000" --hiveconf hive.exec.dynamic.partition.mode=nonstrict -e "\n    CREATE EXTERNAL TABLE IF NOT EXISTS transactions (\n        transaction_id STRING,\n        date_time STRING,\n        amount DOUBLE,\n        currency STRING,\n        merchant_details STRING,\n        customer_id STRING,\n        transaction_type STRING,\n        location STRING\n    )\n    PARTITIONED BY (batch_id STRING)\n    STORED AS PARQUET\n    LOCATION \'/data/transactions/transactions_batch_0\';\n    ALTER TABLE transactions ADD IF NOT EXISTS PARTITION (batch_id=\'batch_20250320_014458\') LOCATION \'/data/transactions/transactions_batch_0\';"\n    ']
[2025-03-20T02:35:06.313+0000] {subprocess.py:86} INFO - Output:
[2025-03-20T02:35:06.412+0000] {subprocess.py:93} INFO - /opt/hive/bin/hive: line 122: [: /opt/hive/lib/hive-exec-2.3.9-core.jar: binary operator expected
[2025-03-20T02:35:06.413+0000] {subprocess.py:93} INFO - /opt/hive/bin/hive: line 127: [: /opt/hive/lib/hive-metastore-2.3.9.jar: binary operator expected
[2025-03-20T02:35:06.414+0000] {subprocess.py:93} INFO - /opt/hive/bin/hive: line 133: [: /opt/hive/lib/hive-cli-2.3.9.jar: binary operator expected
[2025-03-20T02:35:08.086+0000] {subprocess.py:93} INFO - SLF4J: Class path contains multiple SLF4J bindings.
[2025-03-20T02:35:08.087+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-03-20T02:35:08.088+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-03-20T02:35:08.089+0000] {subprocess.py:93} INFO - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[2025-03-20T02:35:08.282+0000] {subprocess.py:93} INFO - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
[2025-03-20T02:35:09.199+0000] {subprocess.py:93} INFO - Exception in thread "main" java.lang.ClassNotFoundException: /opt/hive/lib/hive-beeline-3/1/3/jar
[2025-03-20T02:35:09.200+0000] {subprocess.py:93} INFO - 	at java.lang.Class.forName0(Native Method)
[2025-03-20T02:35:09.201+0000] {subprocess.py:93} INFO - 	at java.lang.Class.forName(Class.java:348)
[2025-03-20T02:35:09.201+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.RunJar.run(RunJar.java:316)
[2025-03-20T02:35:09.202+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
[2025-03-20T02:35:09.255+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-20T02:35:09.268+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-20T02:35:09.272+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transactions_pipeline, task_id=create_hive_table, execution_date=20250320T014458, start_date=20250320T023506, end_date=20250320T023509
[2025-03-20T02:35:09.287+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 226 for task create_hive_table (Bash command failed. The command returned a non-zero exit code 1.; 1732)
[2025-03-20T02:35:09.308+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-20T02:35:09.335+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
